#!/bin/bash
set -e

# Configure ENV variable to set on-premise solution
export HARBUR_URL=${HARBUR_URL:-https://cloud.harbur.io}

endpoint="s"
command="docker-compose"
OUTPUT_FILENAME="docker-compose.yml"

if [[ $1 == '-f' ]]; then
  endpoint="f"
  command="fleetctl"
  shift
fi

namespace=$(echo "$1" | cut -d':' -f1)
username=$(echo "$namespace" | cut -d'/' -f1)
title=$(echo "$namespace" | cut -d'/' -f2)
if [[ $1 == *:* ]]
then
  version=$(echo "$1" | cut -d':' -f2)
else
  version="latest"
fi

shift
args=$*

if [[ $command == "fleetctl" ]]
then
  OUTPUT_FILENAME="${title}.service"
fi

login () {
  if [[ -n $HARBUR_USER ]]; then
    curl -s -b ~/.harbur/cookies.txt -c ~/.harbur/cookies.txt --data "email=${HARBUR_USER}&password=${HARBUR_PASSWD}" ${HARBUR_URL}/api/login > /dev/null
  fi
}

appRun () {
  login
  HARBUR_DIR=$HOME/.harbur/$namespace
  mkdir -p $HARBUR_DIR
  curl -b ~/.harbur/cookies.txt -c ~/.harbur/cookies.txt -s ${HARBUR_URL}/api/${endpoint}/${namespace}/${version} > ${HARBUR_DIR}/${OUTPUT_FILENAME}
  cd ${HARBUR_DIR}
  ${command} ${args}
}

appHelp () {
  echo "Harbur CLI tool - container stacks management with Docker Compose."
  echo ""
  echo "Usage:"
  echo "  harbur IMAGE COMMAND"
  echo ""
  echo "Download a docker-compose.yml and launch docker-compose command on it."
  echo "If docker-compose.yml is already downloaded it is cached at ~/.harbur/ directory"
  echo "IMAGE is defined by 'namespace/repo:version'"
}


if [ $# -gt 0 ]; then
	appRun $*
else
	appHelp
fi

exit 0
